### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by wiktor-k** [xdbob/mkinitcpio-gnupg#3]
Hello,

I've found your project recently and would like to contribute some small things here and there but I've noticed that the project is missing a license.

Could you add one? GitHub has a nice resource for this: https://choosealicense.com

**Comment by xdbob** [comment]
I am used to licence most of my projects under `GPLv3` but with **that** small amount of "code", I'm open to Licence it under a non-copyleft license like BSD or MIT if you wish

**Comment by wiktor-k** [comment]
Hi, I actually don't mind `GPLv3`, it's fine by me.

Thanks!

**Comment by xdbob** [comment]
Fixed in 9776cc53a247d85c835cf412380e4b6ec383e3f5
